apiVersion: v1
kind: Service
metadata: {name: {{ include "aegisllm.fullname" . }} }
spec:
  selector: {app: {{ include "aegisllm.name" . }}}
  ports: [{port: {{ .Values.service.port }}, targetPort: 8080}]
